### ISSUE TITLE
Article "NX(No-eXecute)的实现分析" had gone.

### ISSUE THREAD

**Issue by persmule** [hardenedlinux/hardenedlinux.github.io#43]
In "[content](http://hardenedlinux.org/about3/)", there is an article "[NX(No-eXecute)的实现分析](http://hardenedlinux.org/gnulinux-security/2016/06/01/NX-analysis.html)", but http 404 is replied when accessing.

**Comment by citypw** [comment]
Thanks for the reporting. It's fixed.
