### ISSUE TITLE
Fix the apostrophe please

### ISSUE THREAD

**Issue by wsong83** [hardenedlinux/hardenedlinux.github.io#71]
Not sure if it is just me or every one. I am beginning to be annoyed by the prolonged apostrophe in the actual webpage.

Some something in markdown like this
`( because it’d be harmful to OEM’s interest?)`
Is rendered into
`( because it’ d be harmful to OEM’ s interest?)`
There is an obvious blank after `'`.

What I believe this is caused by the default font used to support Chinese as well as English.
Especially I think it might because this setting?
The `source-han-sans-simplified-c` used in `_site/css/font.css` and `css/font.css`?

**Comment by citypw** [comment]
I don't know what fonts should be used here. @n3o4po11o @wnereiz  any idea?

**Comment by ghost** [comment]
Notice: It is a quick fix. I didn't test on my environment. But I think there will not have problem cause only fonts changed.

**Comment by citypw** [comment]
It seems working fine. Thanks!

**Comment by citypw** [comment]
Oops, it seems not fixed.

**Comment by ghost** [comment]
It was in css/style.css, maybe ...

**Comment by wsong83** [comment]
Yeah, it is fixed. Thanks guys!

**Comment by citypw** [comment]
You're welcome.
